name: gh

services:
  test:
    container_name: test
    env_file:
      - .env
    ports:
      - $PORT:$PORT
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start
    environment:
      - NODE_ENV=production
