services:
  github-actions:
    container_name: github-actions
    env_file:
      - .env
    ports:
      - $PORT:$PORT
    volumes:
      - .:/app/
      - /app/node_modules
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start
