name: build and push
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set repository name variable
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | cut -d '/' -f 2)
          echo "REPO_NAME=${REPO_NAME}" >> $GITHUB_ENV

      - name: Update version in server
        id: update_version
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            curl -X POST http://localhost:9988/service/${{ env.REPO_NAME }} -H "Content-Type: application/json" -d "{\"commit\": \"${{ github.sha }}\", \"merge\": \"${{ github.event.pull_request.merged }}\"}"
          # script: curl -X GET http://localhost:9988/service/${{ env.REPO_NAME }}
        
