name: build and push
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: alxnnewmax/${{ secrets.DOCKER_IMAGE }}
          # tags: ${{  github.ref_name }}

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Update version in server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: cd Desktop/core-services/${{ secrets.DOCKER_IMAGE }} && git pull origin master && docker ps && docker run -p 5320:5320 -d --rm --name test alxnnewmax/${{ secrets.DOCKER_IMAGE }}:master
          # script: cd Desktop/core-services/${{ secrets.DOCKER_IMAGE }} && git pull origin master && "C:\Program Files\Git\bin\sh.exe" docker-up.sh
          # script: cd Desktop/core-services/${{ secrets.DOCKER_IMAGE }} && git pull origin master && docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }} && docker compose up -d
          # script: cd Desktop/core-services/${{ secrets.DOCKER_IMAGE }} && git pull origin master && echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin && docker compose up -d
          # script: cd Desktop/core-services/${{ secrets.DOCKER_IMAGE }} && git pull origin master && docker compose up -d

      # - name: Deploy to remote server
      #   uses: appleboy/ssh-action@v1.0.3
      #   with:
      #     host: ${{ secrets.SERVER_HOST }}
      #     username: ${{ secrets.SERVER_USER }}
      #     password: ${{ secrets.SERVER_PASSWORD }}
      #     script: |
      #       docker pull alxnnewmax/${{ secrets.DOCKER_IMAGE }}:master
      #       docker run -d --name my-container alxnnewmax/${{ secrets.DOCKER_IMAGE }}:master

  send_message:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Send message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: Деплой успешно выполнен!
